version: '3.8'

services:
  db:
    image: mysql:8.0.1
    restart: unless-stopped
    container_name: laravel_db
    ports:
      - 3306:3306
    networks:
      - laravel_network
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel       
      MYSQL_USER: laravel         
      MYSQL_PASSWORD: password  
      MYSQL_ROOT_PASSWORD: password  

  php:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html/src
    networks:
      - laravel_network
    ports:
      - "8888:80"

volumes:
  mysql_data:

networks:
  laravel_network:
